parameters:
- name: Pattern
  type: string
  default: '*.dll'

steps:
- task: PowerShell@2
  displayName: 'KYLE - Generate Test Files'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.BinariesDirectory)'
    script: |
      $working_directory='$(Build.BinariesDirectory)\kyle'

      #$working_directory="D:\Features\EngineeringSystem\Task DLLs in maven" + "\kyle"

      New-Item -Path $working_directory -ItemType Directory

      Write-Host "Generating fake jar files."
      Out-File -FilePath $working_directory"\test1.jar" -InputObject "this is a test1 jar file."
      Write-Host "Generated fake jar files."

      <#
      Write-Host "Generating fake dll files."
      Out-File -FilePath $working_directory"\test2.dll" -InputObject "this is a test2 dll file."
      Write-Host "Generated fake dll files."
      #>


- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
  displayName: "KYLE - ESRP Basic Usage"
  inputs:
    ConnectedServiceName: 'OnnxrunTimeCodeSign_20240611'
    AppRegistrationClientId: '53d54d02-978d-4305-8572-583cf6711c4f'
    AppRegistrationTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
    AuthAKVName: 'buildkeyvault'
    AuthCertName: '53d54d02-SSL-AutoRotate'
    AuthSignCertName: '53d54d02-978d-4305-8572-583cf6711c4f'
    signConfigType: inlineSignParams
    inlineOperation: |
      [
        {
          "keyCode": "CP-447347-Java",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]

    FolderPath: '$(Build.BinariesDirectory)\kyle'
    Pattern: ${{ parameters.Pattern }}
    SessionTimeout: 90
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2'
    MaxConcurrency: 25

- task: PublishPipelineArtifact@1
  displayName: 'KYLE - Publish Artifacts'
  inputs:
    targetPath: '$(Build.BinariesDirectory)\kyle'
    artifactName: 'debug_artifacts'

- task: PowerShell@2
  displayName: 'KYLE - Ending Pipeline Running'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.BinariesDirectory)'
    script: |
      exit 1
