parameters:
  - name: JarFileDirectory
    type: string

  - name: WorkingDirectory
    type: string

steps:
  - task: AzureKeyVault@2
    displayName: 'Get GPG signing key'
    inputs:
      azureSubscription: 'OnnxrunTimeCodeSign_20240611'
      KeyVaultName: 'ort-release'
      SecretsFilter: 'java-pgp-pwd,java-pgp-key'
      RunAsPreJob: false

  - task: PowerShell@2
      displayName: 'Sign jar files GPG'
      inputs:
        targetType: filePath
        filePath: $(Build.SourcesDirectory)\tools\ci_build\github\windows\jar_maven_signing.ps1
        arguments: '${{ parameters.JarFileDirectory }} ${{ parameters.WorkingDirectory }}'
        workingDirectory: '$(Build.BinariesDirectory)'
        failOnStderr: true
        showWarnings: true
